"""Mirror the local kanban DB into the repo so any agent can resume.

  python scripts/board.py export   # ~/.claude/kanban-dbs/<project>.db -> docs/board.json + docs/BOARD.md
  python scripts/board.py import   # docs/board.json -> local DB (for a fresh machine/agent)
  python scripts/board.py move <id> <status> [note]
"""
import json
import os
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECT = "jev-double-checker"
DB = Path(os.path.expanduser(f"~/.claude/kanban-dbs/{PROJECT}.db"))
JSON_PATH = ROOT / "docs" / "board.json"
MD_PATH = ROOT / "docs" / "BOARD.md"
FIELDS = ["id", "title", "status", "priority", "level", "rank", "description", "done_when",
          "implementation_notes", "notes", "updated_at", "completed_at"]
COLUMNS = ["impl", "impl_review", "test", "plan_review", "plan", "todo", "done"]

SCHEMA = """CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT, project TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'todo',
  priority TEXT NOT NULL DEFAULT 'medium', description TEXT, plan TEXT, implementation_notes TEXT, tags TEXT DEFAULT '[]',
  review_comments TEXT DEFAULT '[]', plan_review_comments TEXT DEFAULT '[]', test_results TEXT DEFAULT '[]', agent_log TEXT DEFAULT '[]',
  notes TEXT DEFAULT '[]', current_agent TEXT, plan_review_count INTEGER NOT NULL DEFAULT 0, impl_review_count INTEGER NOT NULL DEFAULT 0,
  level INTEGER NOT NULL DEFAULT 3, attachments TEXT DEFAULT '[]', decision_log TEXT, done_when TEXT, rank INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now')), updated_at TEXT DEFAULT (datetime('now')), started_at TEXT, planned_at TEXT,
  reviewed_at TEXT, tested_at TEXT, completed_at TEXT);"""


def connect():
    DB.parent.mkdir(parents=True, exist_ok=True)
    c = sqlite3.connect(DB)
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    return c


def export():
    c = connect()
    rows = [dict(r) for r in c.execute(
        f"SELECT {','.join(FIELDS)} FROM tasks WHERE project=? ORDER BY rank, id", (PROJECT,))]
    JSON_PATH.write_text(json.dumps(rows, indent=2, ensure_ascii=False) + "\n")
    lines = ["# Kanban board (mirrored from local SQLite)", "",
             "Generated by `python scripts/board.py export`. Source of truth for agents without the local DB:",
             "run `python scripts/board.py import` to recreate it.", "",
             "| ID | Status | Lvl | Title | Done when |", "|---|---|---|---|---|"]
    order = {s: i for i, s in enumerate(COLUMNS)}
    for r in sorted(rows, key=lambda r: (order.get(r["status"], 9), r["rank"])):
        lines.append(f"| {r['id']} | {r['status']} | L{r['level']} | {r['title']} | {r['done_when'] or ''} |")
    MD_PATH.write_text("\n".join(lines) + "\n")
    print(f"exported {len(rows)} tasks")


def import_():
    c = connect()
    rows = json.loads(JSON_PATH.read_text())
    for r in rows:
        cols = [f for f in FIELDS if f in r]
        c.execute(f"INSERT OR REPLACE INTO tasks (project,{','.join(cols)}) VALUES (?{',?' * len(cols)})",
                  [PROJECT] + [r[f] for f in cols])
    c.commit()
    print(f"imported {len(rows)} tasks into {DB}")


def move(task_id, status, note=None):
    c = connect()
    extra = ", completed_at=datetime('now')" if status == "done" else ""
    c.execute(f"UPDATE tasks SET status=?, updated_at=datetime('now'){extra} WHERE id=? AND project=?",
              (status, int(task_id), PROJECT))
    if note:
        c.execute("UPDATE tasks SET implementation_notes=? WHERE id=? AND project=?", (note, int(task_id), PROJECT))
    c.commit()
    export()


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "export"
    {"export": export, "import": import_}.get(cmd, lambda: move(*sys.argv[2:]))()
